// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKvCPu83VZuyRF0GGmD_vBBCVL-AziYk',
    appId: '1:491406060308:web:24a57f607e4c7aa0efb001',
    messagingSenderId: '491406060308',
    projectId: 'medicinus-85d33',
    authDomain: 'medicinus-85d33.firebaseapp.com',
    databaseURL: 'https://medicinus-85d33-default-rtdb.firebaseio.com',
    storageBucket: 'medicinus-85d33.firebasestorage.app',
    measurementId: 'G-MT5KQCKSPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dPocQm0momaLLsqGssio1Hu6zE8PTqs',
    appId: '1:491406060308:android:5fe93b47e70b16acefb001',
    messagingSenderId: '491406060308',
    projectId: 'medicinus-85d33',
    databaseURL: 'https://medicinus-85d33-default-rtdb.firebaseio.com',
    storageBucket: 'medicinus-85d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0r6mzTc9gtn-UvKbKF0nUSTDiMgpHdE',
    appId: '1:491406060308:ios:b7a266053d9cdc22efb001',
    messagingSenderId: '491406060308',
    projectId: 'medicinus-85d33',
    databaseURL: 'https://medicinus-85d33-default-rtdb.firebaseio.com',
    storageBucket: 'medicinus-85d33.firebasestorage.app',
    iosClientId: '491406060308-uqe6v691mbr04jc06v1hsk4s31p1smo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicinus',
  );
}
